export default [
	{city: ['Ukraine', 'Kiev']},
	{city: ['Ukraine', 'Kharkov']},
	{city: ['Ukraine', 'Lviv']},
	{city: ['Ukraine', 'Odessa']},
	{city: ['Russia', 'Moscow']},
	{city: ['Russia', 'St. Peterburg']},
	{city: ['Russia', 'Vladivostok']},
	{city: ['Russia', 'Omsk']},
	{city: ['USA', 'Vashington']},
	{city: ['USA', 'New Yourk']},
	{city: ['USA', 'Las Vegas']},
	{city: ['USA', 'Miamy']},
	{city: ['USA', 'San Francisko']},
	{city: ['USA', 'Portland']},
	{city: ['Canada', 'Toronto']},
	{city: ['Canada', 'Vancouver']},
	{city: ['United Kingdom', 'London']},
	{city: ['United Kingdom', 'Liverpool']},
	{city: ['United Kingdom', 'Manchester']},
	{city: ['France', 'Paris']},
	{city: ['Germany', 'Berlin']},
	{city: ['Germany', 'Frankfurt']},
	{city: ['Germany', 'Hamburg']},
	{city: ['Italy', 'Rome']},
	{city: ['Poland', 'Warsaw']},
	{city: ['Belarus', 'Minsk']},
	{city: ['Turkey', 'Ankara']},
	{city: ['Spain', 'Madrid']},
	{city: ['China', 'Hong Kong']},
	{city: ['China', 'Beijing']},
	{city: ['India', 'New Delhi']},
	{city: ['Egypt', 'Cairo']},
	{city: ['Brazil', 'Rio De Janeiro']},
]
